### ISSUE TITLE
nitpicks

### ISSUE THREAD

**Issue by adone** [bl1ndy/meta_ruby#1]
1. `respond_to_missing?`
с ним везде проблема, например
```ruby
def respond_to_missing?(name)
  respond_to?(name)
end
```
здесь `respond_to_missing?` вообще не нужен, если объект и так отвечает на метод 
судя по задумке, это часть `actions` API
и здесь `respond_to_missing?` по факту бесполезен

2. `actions`
с ним другая проблема
в момент вызова `yield` вот здесь
```ruby
def actions(&)
  yield
end
```
контекст выполнения теряется
лишь по стечению обстоятельств мы остаемся в `Builder` (из-за DSL porxy)
но это можно испортить, например, вот так
```ruby
define_actions = -> { ... }

define_attributes do
  count do
    actions(&define_actions)
  end
end
```
внутри DSL не стоит просто так взывать `yield`
лучше всегда готовить некий объект для выполнения любого блока кода
P.S. на обычный код это не распространяется, там не нужно заботиться о контекстах

3. создание методов
можно пропустить один шаг вот тут
```ruby
@context.define_method(name) do
  instance_exec(&block)
end
```
и сделать вот так
```ruby
@context.define_method(name, &block)
```
чуть менее многословно)

4.  создание методов в `enum`
да, это логично, НО лучше держать все сопряженные операции ближе к друг другу
по структуре метода `define_attributes` явно вырисовывается, что вся инициализация произойдет в `builder.init`
но по факту часть методов появится до этого момента
да, все работает, но это неожиданный сюрприз для любого, работающего с нашим кодом
ситуация может стать хуже, если в какой либо момент в будущем код распределится по нескольким файлам

5. вычисление `default`
это совершено не критичная проблема, но замалчивать её не стоит
блок, переданный в `default`, может быть "тяжелым"
вычислять его просто так не стоит, потому лучше воспользоваться методом `fetch`
```ruby
value = args.fetch(attr) do
  # call default
end
```

в остальном все отлично 👍

**Comment by bl1ndy** [comment]
Внес изменения https://github.com/bl1ndy/meta_ruby/commit/5b8a5682f54473cf7021ea44d5da261df76d657c
